
using MailKit.Net.Smtp;
using MailKit.Security;
using MimeKit;
using Microsoft.Extensions.Configuration;
using Application.ServiceHelper;
using System.Text;

namespace Infrastructure.Helper
{
    public class EmailHelper : IEmailHelper
    {
        public async Task<string> SendEmail(string toEmail, string mailSubject, StringBuilder mailBody , IConfiguration config)
        {
            try
            {
                var smtpServer = config["EmailSettings:SmtpServer"];
                var port = int.Parse(config["EmailSettings:Port"]);
                var fromMail = config["EmailSettings:Username"];
                var password = config["EmailSettings:Password"];

                var email = new MimeMessage();
                email.From.Add(new MailboxAddress("Halo POS", fromMail));
                email.To.Add(new MailboxAddress("", toEmail));
                email.Subject = mailSubject;
                var builder = new BodyBuilder();
                builder.HtmlBody = mailBody.ToString();
                //email.Body = new TextPart("html") { Text = mailBody };
                email.Body = builder.ToMessageBody();

                using var smtp = new SmtpClient();
                await smtp.ConnectAsync(smtpServer, port, SecureSocketOptions.StartTls);
                await smtp.AuthenticateAsync(fromMail, password);
                await smtp.SendAsync(email);
                await smtp.DisconnectAsync(true);

                return "Email sent successfully!";
            }
            catch (Exception ex)
            {
                return $"Email sending failed. Error: {ex.Message}";
            }
        }

        public StringBuilder SetBodyEmailActivateAccount(string link)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<!doctype html>" + Environment.NewLine);
            sb.Append("<html lang=\"en\">" + Environment.NewLine);
            sb.Append("  <head>" + Environment.NewLine);
            sb.Append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" + Environment.NewLine);
            sb.Append("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("      <title>Simple Transactional Email</title>" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    <style media=\"all\" type=\"text/css\">" + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    GLOBAL RESETS" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    body {" + Environment.NewLine);
            sb.Append("      font-family: Helvetica, sans-serif;" + Environment.NewLine);
            sb.Append("      -webkit-font-smoothing: antialiased;" + Environment.NewLine);
            sb.Append("      font-size: 16px;" + Environment.NewLine);
            sb.Append("      line-height: 1.3;" + Environment.NewLine);
            sb.Append("      -ms-text-size-adjust: 100%;" + Environment.NewLine);
            sb.Append("      -webkit-text-size-adjust: 100%;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    table {" + Environment.NewLine);
            sb.Append("      border-collapse: separate;" + Environment.NewLine);
            sb.Append("      mso-table-lspace: 0pt;" + Environment.NewLine);
            sb.Append("      mso-table-rspace: 0pt;" + Environment.NewLine);
            sb.Append("      width: 100%;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    table td {" + Environment.NewLine);
            sb.Append("      font-family: Helvetica, sans-serif;" + Environment.NewLine);
            sb.Append("      font-size: 16px;" + Environment.NewLine);
            sb.Append("      vertical-align: top;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    BODY & CONTAINER" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    body {" + Environment.NewLine);
            sb.Append("      background-color: #f4f5f6;" + Environment.NewLine);
            sb.Append("      margin: 0;" + Environment.NewLine);
            sb.Append("      padding: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .body {" + Environment.NewLine);
            sb.Append("      background-color: #f4f5f6;" + Environment.NewLine);
            sb.Append("      width: 100%;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .container {" + Environment.NewLine);
            sb.Append("      margin: 0 auto !important;" + Environment.NewLine);
            sb.Append("      max-width: 600px;" + Environment.NewLine);
            sb.Append("      padding: 0;" + Environment.NewLine);
            sb.Append("      padding-top: 24px;" + Environment.NewLine);
            sb.Append("      width: 600px;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .content {" + Environment.NewLine);
            sb.Append("      box-sizing: border-box;" + Environment.NewLine);
            sb.Append("      display: block;" + Environment.NewLine);
            sb.Append("      margin: 0 auto;" + Environment.NewLine);
            sb.Append("      max-width: 600px;" + Environment.NewLine);
            sb.Append("      padding: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    HEADER, FOOTER, MAIN" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .main {" + Environment.NewLine);
            sb.Append("      background: #ffffff;" + Environment.NewLine);
            sb.Append("      border: 1px solid #eaebed;" + Environment.NewLine);
            sb.Append("      border-radius: 16px;" + Environment.NewLine);
            sb.Append("      width: 100%;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .wrapper {" + Environment.NewLine);
            sb.Append("      box-sizing: border-box;" + Environment.NewLine);
            sb.Append("      padding: 24px;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .footer {" + Environment.NewLine);
            sb.Append("      clear: both;" + Environment.NewLine);
            sb.Append("      padding-top: 24px;" + Environment.NewLine);
            sb.Append("      text-align: center;" + Environment.NewLine);
            sb.Append("      width: 100%;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .footer td," + Environment.NewLine);
            sb.Append("    .footer p," + Environment.NewLine);
            sb.Append("    .footer span," + Environment.NewLine);
            sb.Append("    .footer a {" + Environment.NewLine);
            sb.Append("      color: #9a9ea6;" + Environment.NewLine);
            sb.Append("      font-size: 16px;" + Environment.NewLine);
            sb.Append("      text-align: center;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    TYPOGRAPHY" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    p {" + Environment.NewLine);
            sb.Append("      font-family: Helvetica, sans-serif;" + Environment.NewLine);
            sb.Append("      font-size: 16px;" + Environment.NewLine);
            sb.Append("      font-weight: normal;" + Environment.NewLine);
            sb.Append("      margin: 0;" + Environment.NewLine);
            sb.Append("      margin-bottom: 16px;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    a {" + Environment.NewLine);
            sb.Append("      color: #0867ec;" + Environment.NewLine);
            sb.Append("      text-decoration: underline;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    BUTTONS" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn {" + Environment.NewLine);
            sb.Append("      box-sizing: border-box;" + Environment.NewLine);
            sb.Append("      min-width: 100% !important;" + Environment.NewLine);
            sb.Append("      width: 100%;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn > tbody > tr > td {" + Environment.NewLine);
            sb.Append("      padding-bottom: 16px;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn table {" + Environment.NewLine);
            sb.Append("      width: auto;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn table td {" + Environment.NewLine);
            sb.Append("      background-color: #ffffff;" + Environment.NewLine);
            sb.Append("      border-radius: 4px;" + Environment.NewLine);
            sb.Append("      text-align: center;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn a {" + Environment.NewLine);
            sb.Append("      background-color: #ffffff;" + Environment.NewLine);
            sb.Append("      border: solid 2px #0867ec;" + Environment.NewLine);
            sb.Append("      border-radius: 4px;" + Environment.NewLine);
            sb.Append("      box-sizing: border-box;" + Environment.NewLine);
            sb.Append("      color: #0867ec;" + Environment.NewLine);
            sb.Append("      cursor: pointer;" + Environment.NewLine);
            sb.Append("      display: inline-block;" + Environment.NewLine);
            sb.Append("      font-size: 16px;" + Environment.NewLine);
            sb.Append("      font-weight: bold;" + Environment.NewLine);
            sb.Append("      margin: 0;" + Environment.NewLine);
            sb.Append("      padding: 12px 24px;" + Environment.NewLine);
            sb.Append("      text-decoration: none;" + Environment.NewLine);
            sb.Append("      text-transform: capitalize;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn-primary table td {" + Environment.NewLine);
            sb.Append("      background-color: #0867ec;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .btn-primary a {" + Environment.NewLine);
            sb.Append("      background-color: #0867ec;" + Environment.NewLine);
            sb.Append("      border-color: #0867ec;" + Environment.NewLine);
            sb.Append("      color: #ffffff;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    @media all {" + Environment.NewLine);
            sb.Append("      .btn-primary table td:hover {" + Environment.NewLine);
            sb.Append("        background-color: #ec0867 !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .btn-primary a:hover {" + Environment.NewLine);
            sb.Append("        background-color: #ec0867 !important;" + Environment.NewLine);
            sb.Append("        border-color: #ec0867 !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    OTHER STYLES THAT MIGHT BE USEFUL" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .last {" + Environment.NewLine);
            sb.Append("      margin-bottom: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .first {" + Environment.NewLine);
            sb.Append("      margin-top: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .align-center {" + Environment.NewLine);
            sb.Append("      text-align: center;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .align-right {" + Environment.NewLine);
            sb.Append("      text-align: right;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .align-left {" + Environment.NewLine);
            sb.Append("      text-align: left;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .text-link {" + Environment.NewLine);
            sb.Append("      color: #0867ec !important;" + Environment.NewLine);
            sb.Append("      text-decoration: underline !important;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .clear {" + Environment.NewLine);
            sb.Append("      clear: both;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .mt0 {" + Environment.NewLine);
            sb.Append("      margin-top: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .mb0 {" + Environment.NewLine);
            sb.Append("      margin-bottom: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .preheader {" + Environment.NewLine);
            sb.Append("      color: transparent;" + Environment.NewLine);
            sb.Append("      display: none;" + Environment.NewLine);
            sb.Append("      height: 0;" + Environment.NewLine);
            sb.Append("      max-height: 0;" + Environment.NewLine);
            sb.Append("      max-width: 0;" + Environment.NewLine);
            sb.Append("      opacity: 0;" + Environment.NewLine);
            sb.Append("      overflow: hidden;" + Environment.NewLine);
            sb.Append("      mso-hide: all;" + Environment.NewLine);
            sb.Append("      visibility: hidden;" + Environment.NewLine);
            sb.Append("      width: 0;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    .powered-by a {" + Environment.NewLine);
            sb.Append("      text-decoration: none;" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    RESPONSIVE AND MOBILE FRIENDLY STYLES" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    @media only screen and (max-width: 640px) {" + Environment.NewLine);
            sb.Append("      .main p," + Environment.NewLine);
            sb.Append("      .main td," + Environment.NewLine);
            sb.Append("      .main span {" + Environment.NewLine);
            sb.Append("        font-size: 16px !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .wrapper {" + Environment.NewLine);
            sb.Append("        padding: 8px !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .content {" + Environment.NewLine);
            sb.Append("        padding: 0 !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .container {" + Environment.NewLine);
            sb.Append("        padding: 0 !important;" + Environment.NewLine);
            sb.Append("        padding-top: 8px !important;" + Environment.NewLine);
            sb.Append("        width: 100% !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .main {" + Environment.NewLine);
            sb.Append("        border-left-width: 0 !important;" + Environment.NewLine);
            sb.Append("        border-radius: 0 !important;" + Environment.NewLine);
            sb.Append("        border-right-width: 0 !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .btn table {" + Environment.NewLine);
            sb.Append("        max-width: 100% !important;" + Environment.NewLine);
            sb.Append("        width: 100% !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .btn a {" + Environment.NewLine);
            sb.Append("        font-size: 16px !important;" + Environment.NewLine);
            sb.Append("        max-width: 100% !important;" + Environment.NewLine);
            sb.Append("        width: 100% !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    /* -------------------------------------" + Environment.NewLine);
            sb.Append("    PRESERVE THESE STYLES IN THE HEAD" + Environment.NewLine);
            sb.Append("------------------------------------- */" + Environment.NewLine);
            sb.Append("    " + Environment.NewLine);
            sb.Append("    @media all {" + Environment.NewLine);
            sb.Append("      .ExternalClass {" + Environment.NewLine);
            sb.Append("        width: 100%;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .ExternalClass," + Environment.NewLine);
            sb.Append("      .ExternalClass p," + Environment.NewLine);
            sb.Append("      .ExternalClass span," + Environment.NewLine);
            sb.Append("      .ExternalClass font," + Environment.NewLine);
            sb.Append("      .ExternalClass td," + Environment.NewLine);
            sb.Append("      .ExternalClass div {" + Environment.NewLine);
            sb.Append("        line-height: 100%;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      .apple-link a {" + Environment.NewLine);
            sb.Append("        color: inherit !important;" + Environment.NewLine);
            sb.Append("        font-family: inherit !important;" + Environment.NewLine);
            sb.Append("        font-size: inherit !important;" + Environment.NewLine);
            sb.Append("        font-weight: inherit !important;" + Environment.NewLine);
            sb.Append("        line-height: inherit !important;" + Environment.NewLine);
            sb.Append("        text-decoration: none !important;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("      #MessageViewBody a {" + Environment.NewLine);
            sb.Append("        color: inherit;" + Environment.NewLine);
            sb.Append("        text-decoration: none;" + Environment.NewLine);
            sb.Append("        font-size: inherit;" + Environment.NewLine);
            sb.Append("        font-family: inherit;" + Environment.NewLine);
            sb.Append("        font-weight: inherit;" + Environment.NewLine);
            sb.Append("        line-height: inherit;" + Environment.NewLine);
            sb.Append("      }" + Environment.NewLine);
            sb.Append("    }" + Environment.NewLine);
            sb.Append("    </style>" + Environment.NewLine);
            sb.Append("  </head>" + Environment.NewLine);
            sb.Append("  <body>" + Environment.NewLine);
            sb.Append("    <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"body\">" + Environment.NewLine);
            sb.Append("      <tr>" + Environment.NewLine);
            sb.Append("        <td>&nbsp;</td>" + Environment.NewLine);
            sb.Append("        <td class=\"container\">" + Environment.NewLine);
            sb.Append("          <div class=\"content\">" + Environment.NewLine);
            sb.Append("" + Environment.NewLine);
            sb.Append("            <!-- START CENTERED WHITE CONTAINER -->" + Environment.NewLine);
            sb.Append("            <span class=\"preheader\"></span>" + Environment.NewLine);
            sb.Append("            <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"main\">" + Environment.NewLine);
            sb.Append("" + Environment.NewLine);
            sb.Append("              <!-- START MAIN CONTENT AREA -->" + Environment.NewLine);
            sb.Append("              <tr>" + Environment.NewLine);
            sb.Append("                <td class=\"wrapper\">" + Environment.NewLine);
            sb.Append("                  <h1>Halo POS</h1>" + Environment.NewLine);
            sb.Append("                  <p>Thank you for register your please click button below to Activate your Account</p>" + Environment.NewLine);
            sb.Append("                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"btn btn-primary\">" + Environment.NewLine);
            sb.Append("                    <tbody>" + Environment.NewLine);
            sb.Append("                      <tr>" + Environment.NewLine);
            sb.Append("                        <td align=\"left\">" + Environment.NewLine);
            sb.Append("                          <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">" + Environment.NewLine);
            sb.Append("                            <tbody>" + Environment.NewLine);
            sb.Append("                              <tr>" + Environment.NewLine);
            sb.Append("                                <td> " + Environment.NewLine);
            sb.Append("                                  <a taget=\"_blank\" href=\""+link+"\">Activate</a>" + Environment.NewLine);
            sb.Append("                              </tr>" + Environment.NewLine);
            sb.Append("                            </tbody>" + Environment.NewLine);
            sb.Append("                          </table>" + Environment.NewLine);
            sb.Append("                        </td>" + Environment.NewLine);
            sb.Append("                      </tr>" + Environment.NewLine);
            sb.Append("                    </tbody>" + Environment.NewLine);
            sb.Append("                  </table>" + Environment.NewLine);
            sb.Append("                  <p>.</p>" + Environment.NewLine);
            sb.Append("                  <p></p>" + Environment.NewLine);
            sb.Append("                </td>" + Environment.NewLine);
            sb.Append("              </tr>" + Environment.NewLine);
            sb.Append("" + Environment.NewLine);
            sb.Append("              <!-- END MAIN CONTENT AREA -->" + Environment.NewLine);
            sb.Append("              </table>" + Environment.NewLine);
            sb.Append("" + Environment.NewLine);
            sb.Append("            <!-- START FOOTER -->" + Environment.NewLine);
            sb.Append("            <div class=\"footer\">" + Environment.NewLine);
            sb.Append("              <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">" + Environment.NewLine);
            sb.Append("                <tr>" + Environment.NewLine);
            sb.Append("                  <td class=\"content-block\">" + Environment.NewLine);
            sb.Append("                    <span class=\"apple-link\">Halo POS, Bekasi, West Java, Indonesia</span>" + Environment.NewLine);
            sb.Append("                    " + Environment.NewLine);
            sb.Append("                  </td>" + Environment.NewLine);
            sb.Append("                </tr>" + Environment.NewLine);
            sb.Append("                <tr>" + Environment.NewLine);
            sb.Append("                  <td class=\"content-block powered-by\">" + Environment.NewLine);
            sb.Append("                    Halo POS <a href=\"google.com\">@ 2025</a>" + Environment.NewLine);
            sb.Append("                  </td>" + Environment.NewLine);
            sb.Append("                </tr>" + Environment.NewLine);
            sb.Append("              </table>" + Environment.NewLine);
            sb.Append("            </div>" + Environment.NewLine);
            sb.Append("" + Environment.NewLine);
            sb.Append("            <!-- END FOOTER -->" + Environment.NewLine);
            sb.Append("            " + Environment.NewLine);
            sb.Append("<!-- END CENTERED WHITE CONTAINER --></div>" + Environment.NewLine);
            sb.Append("        </td>" + Environment.NewLine);
            sb.Append("        <td>&nbsp;</td>" + Environment.NewLine);
            sb.Append("      </tr>" + Environment.NewLine);
            sb.Append("    </table>" + Environment.NewLine);
            sb.Append("  </body>" + Environment.NewLine);
            sb.Append("</html>" + Environment.NewLine);
            sb.Append("" + Environment.NewLine);
            return sb;
        }
    }
}
